// 80 frases motivacionais para exibir após cada agendamento
const motivationalPhrases: string[] = [
    "🚀 O sucesso começa com a organização!",
    "🎯 Mais um passo em direção ao seu objetivo!",
    "💪 Produtividade no ponto! Continue assim!",
    "🌟 Cada reunião é uma oportunidade de crescer!",
    "🔥 Você está no caminho certo!",
    "⚡ Quem planeja, conquista!",
    "🏆 Organização é a chave do sucesso!",
    "✨ Brilhe em cada encontro!",
    "🎓 O conhecimento transforma vidas!",
    "💡 Grandes ideias nascem de boas reuniões!",
    "🌈 Seu futuro está sendo construído agora!",
    "🎯 Foco e determinação levam longe!",
    "💎 Cada compromisso é um diamante no seu caminho!",
    "🚀 Decole rumo aos seus sonhos!",
    "🌟 Você é destaque, continue brilhando!",
    "⭐ Excelência é um hábito, não um ato!",
    "🔑 A chave do sucesso é a consistência!",
    "🏅 Campeões se preparam antes da batalha!",
    "💪 Força e foco! Você consegue!",
    "🌱 Cada reunião planta uma semente de sucesso!",
    "🎯 Mire alto, acerte mais alto ainda!",
    "🦁 Seja ousado como um leão!",
    "⚡ Energia positiva em cada compromisso!",
    "🌟 Sua dedicação inspira!",
    "🔥 Queime etapas com organização!",
    "💫 O universo conspira a favor de quem se organiza!",
    "🏆 Vitória é consequência de preparação!",
    "🎓 Aprender é o melhor investimento!",
    "💡 Inovação nasce do planejamento!",
    "🌍 Conectando pessoas, transformando futuros!",
    "🚀 Hora de fazer acontecer!",
    "✨ Momentos planejados, resultados extraordinários!",
    "🎯 Precisão e pontualidade são suas marcas!",
    "💪 A disciplina é a ponte entre metas e conquistas!",
    "🌟 Seu comprometimento faz a diferença!",
    "⭐ Pessoas organizadas dominam o mundo!",
    "🔥 Paixão pelo que faz, excelência no resultado!",
    "🏅 Ouro para quem se prepara!",
    "💎 Seu tempo é precioso, use-o bem!",
    "🌈 Depois da organização, vem o arco-íris!",
    "🎓 Conhecimento é poder, reuniões são energia!",
    "💡 Uma boa reunião muda tudo!",
    "🦁 Rugindo de produtividade!",
    "⚡ Velocidade e eficiência, esse é o caminho!",
    "🌟 Cada dia é uma nova chance de ser incrível!",
    "🚀 Foguete não tem ré! Vai pra cima!",
    "✨ Transformando minutos em resultados!",
    "🎯 Acertou na mosca com esse agendamento!",
    "💪 Mais forte a cada compromisso cumprido!",
    "🏆 Troféu de organização é seu!",
    "🌱 Crescendo um pouco mais a cada dia!",
    "💫 As estrelas estão alinhadas para você!",
    "🔑 Desbloqueando o próximo nível!",
    "🌍 Mudando o mundo, uma reunião por vez!",
    "🔥 Imparável! Ninguém segura você!",
    "⭐ Você é uma estrela em ascensão!",
    "💎 Lapidando o sucesso com cada passo!",
    "🎓 A educação abre portas, a organização as mantém abertas!",
    "💡 Ideias brilhantes merecem agendas brilhantes!",
    "🌈 Cores vibrantes para um futuro vibrante!",
    "🏅 Medalha de ouro em comprometimento!",
    "🦁 Coragem de leão, organização de mestre!",
    "⚡ Raio de produtividade atingiu você!",
    "🚀 3, 2, 1... Sucesso lançado!",
    "✨ Magia acontece quando há planejamento!",
    "🎯 Direto ao ponto, direto ao sucesso!",
    "💪 Seu esforço está valendo a pena!",
    "🌟 Luz própria não precisa apagar a dos outros!",
    "🏆 Vencedor é quem não desiste!",
    "💫 Constelação de conquistas à sua frente!",
    "🌱 Regando os sonhos com ação!",
    "🔑 A porta do sucesso está aberta para você!",
    "🔥 Fogo no jogo! Mandou bem!",
    "⭐ Brilho incomparável!",
    "💎 Raro como um diamante, forte como um leão!",
    "🌍 Sua agenda, seu império!",
    "🎓 Mestrado em organização aprovado!",
    "💡 Gênio da produtividade em ação!",
    "🦁 Valento Academy orgulhosa de você!",
    "⚡ Turbinando sua semana com esse agendamento!",
];

export const getRandomPhrase = (): string => {
    return motivationalPhrases[Math.floor(Math.random() * motivationalPhrases.length)];
};

export default motivationalPhrases;
